# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61gent_service.proto\x12\x0f\x64\x65vops.agent.v1\"Q\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x14\n\x0ctool_call_id\x18\x03 \x01(\t\x12\x11\n\ttool_name\x18\x04 \x01(\t\"\\\n\x0eToolDefinition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x13\n\x0bjson_schema\x18\x03 \x01(\t\x12\x12\n\nrisk_level\x18\x04 \x01(\t\"\xaa\x01\n\rDecideRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x13\n\x0buser_prompt\x18\x02 \x01(\t\x12\x36\n\x14\x63onversation_history\x18\x03 \x03(\x0b\x32\x18.devops.agent.v1.Message\x12\x38\n\x0f\x61vailable_tools\x18\x04 \x03(\x0b\x32\x1f.devops.agent.v1.ToolDefinition\"<\n\x08ToolCall\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x03 \x01(\t\"\x89\x01\n\x0e\x44\x65\x63ideResponse\x12\x0f\n\x07thought\x18\x01 \x01(\t\x12\x17\n\x0fis_final_answer\x18\x02 \x01(\x08\x12\x14\n\x0c\x66inal_answer\x18\x03 \x01(\t\x12\x37\n\x14requested_tool_calls\x18\x04 \x03(\x0b\x32\x19.devops.agent.v1.ToolCall2d\n\x0f\x41IWorkerService\x12Q\n\x0e\x44\x65\x63ideNextStep\x12\x1e.devops.agent.v1.DecideRequest\x1a\x1f.devops.agent.v1.DecideResponseB0Z.github.com/raghavdev/heimdall/proto/v1;agentv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/raghavdev/heimdall/proto/v1;agentv1'
  _globals['_MESSAGE']._serialized_start=40
  _globals['_MESSAGE']._serialized_end=121
  _globals['_TOOLDEFINITION']._serialized_start=123
  _globals['_TOOLDEFINITION']._serialized_end=215
  _globals['_DECIDEREQUEST']._serialized_start=218
  _globals['_DECIDEREQUEST']._serialized_end=388
  _globals['_TOOLCALL']._serialized_start=390
  _globals['_TOOLCALL']._serialized_end=450
  _globals['_DECIDERESPONSE']._serialized_start=453
  _globals['_DECIDERESPONSE']._serialized_end=590
  _globals['_AIWORKERSERVICE']._serialized_start=592
  _globals['_AIWORKERSERVICE']._serialized_end=692
# @@protoc_insertion_point(module_scope)
