// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.26.1
// source: proto/v1/agent_service.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AIWorkerService_DecideNextStep_FullMethodName = "/devops.agent.v1.AIWorkerService/DecideNextStep"
)

// AIWorkerServiceClient is the client API for AIWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIWorkerServiceClient interface {
	DecideNextStep(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*DecideResponse, error)
}

type aIWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIWorkerServiceClient(cc grpc.ClientConnInterface) AIWorkerServiceClient {
	return &aIWorkerServiceClient{cc}
}

func (c *aIWorkerServiceClient) DecideNextStep(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*DecideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecideResponse)
	err := c.cc.Invoke(ctx, AIWorkerService_DecideNextStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIWorkerServiceServer is the server API for AIWorkerService service.
// All implementations must embed UnimplementedAIWorkerServiceServer
// for forward compatibility
type AIWorkerServiceServer interface {
	DecideNextStep(context.Context, *DecideRequest) (*DecideResponse, error)
	mustEmbedUnimplementedAIWorkerServiceServer()
}

// UnimplementedAIWorkerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAIWorkerServiceServer struct {
}

func (UnimplementedAIWorkerServiceServer) DecideNextStep(context.Context, *DecideRequest) (*DecideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecideNextStep not implemented")
}
func (UnimplementedAIWorkerServiceServer) mustEmbedUnimplementedAIWorkerServiceServer() {}

// UnsafeAIWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIWorkerServiceServer will
// result in compilation errors.
type UnsafeAIWorkerServiceServer interface {
	mustEmbedUnimplementedAIWorkerServiceServer()
}

func RegisterAIWorkerServiceServer(s grpc.ServiceRegistrar, srv AIWorkerServiceServer) {
	s.RegisterService(&AIWorkerService_ServiceDesc, srv)
}

func _AIWorkerService_DecideNextStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIWorkerServiceServer).DecideNextStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIWorkerService_DecideNextStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIWorkerServiceServer).DecideNextStep(ctx, req.(*DecideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIWorkerService_ServiceDesc is the grpc.ServiceDesc for AIWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devops.agent.v1.AIWorkerService",
	HandlerType: (*AIWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DecideNextStep",
			Handler:    _AIWorkerService_DecideNextStep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/agent_service.proto",
}
